# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd ui
          npm ci
          npm run build
      - name: Git Commit/Push Changes

      # Commit
      # - uses: actions-x/commit@v2
#         with:
          # The committer's email address
#           email: # default is ${{ github.actor }}@localhost
          # The committer's name
#           name: # default is ${{ github.actor }}
          # The commit message
#           message: # default is Automatically updated using GitHub Actions
          # The branch to push the changes back to, defaults to the current branch
#           branch: # default is ${{ github.ref }}
          # The files to add separated by space, defaults to every file
#           files: # default is .
          # The repository to push the code to, defaults to origin (e.g. this repository)
#           repository: # default is origin
          # The token used to push the code, not needed if you push to the same repository
#           token: # default is ${{ github.token }}
          # Whether to perform force push
#           force: # default is 0
