name: Build / Deploy static site

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd ui
          npm ci
          npm run build
      - uses: actions-x/commit@v2
